version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./fastapi_data:/model


